### ISSUE TITLE
Emoji 対応

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [Qithub-BOT/mastogetter#103]
対応予定です。

**Comment by manzyun** [comment]
よく分かってないですが。まとめページでの投稿に対するEmojiリアクションかなと思って以下を提出します。

# 参考資料

+ [Emoji Mart](https://missive.github.io/emoji-mart/)
    + 超有名かも。[Crieit](https://crieit.net)さんでも使われてるやつです。
+ [Emoji Button](https://joeattardi.github.io/emoji-button/)
    + VanilaJS実装のもの。もしかしたらテキストボックスに挿入前提かも。
+ [GitHubの "emoji-picker" タグ](https://github.com/topics/emoji-picker)
    + 他のものを探す場合は、GitHubでタグ検索で探した方が早いかも。

**Comment by blhsrwznrghfzpr** [comment]
説明を省いてしまったためわかりづらくてすいません……

現状、カスタム絵文字が表示されていないため、その対応をする予定で issue を立てました。
mastodon api レスポンス内に `emojis` なる値があるので、ここを使えば簡単に実装できるはずです

---
qiitadon での表示
![image](https://user-images.githubusercontent.com/7685946/72414018-8ef0ad00-37b4-11ea-853a-74aee04f611d.png)

---
mastogetter での表示
![image](https://user-images.githubusercontent.com/7685946/72414060-a891f480-37b4-11ea-8062-f0800ae603f9.png)
