### ISSUE TITLE
CWが指定されたtootについて取得した場合、警告文箇所が表示に含まれなくなる

### ISSUE THREAD

**Issue by taro-hida** [Qithub-BOT/mastogetter#124]
# 発生する事象
CW (Contents Warning) を指定したtootを取得した場合に、警告文箇所 (ここに警告を書いてください) が表示されないという事象が発生します。

# 発生した例
このまとめにおける最後のtoot
https://qithub-bot.github.io/mastogetter/p.html?i=https://qiitadon.com&t=66z2x_fuyu70,66z2x_1y8p34v,66z2x_295pia6,66z2x_39zhsrv,66z2y_26duw09,66z2y_4i1e9u0,66z2z_nprpr0,66z2z_scvyzk,66z2z_1r2edh0,66z2z_2hrk3dl,66z30_4atzxpi,66z31_1w1t7i4,66z31_3lx6pnm,66z32_2szztwm,66z32_4hhlfte,66z33_4cac87,66z33_3iqa8i0,66z34_1y7hhk6,66z35_17cdzve,66z39_w3cmun,66z3f_45zjbp3

本当はCWが設定されており、以下のような内容🦑
https://qiitadon.com/web/statuses/104031159069148407

# 余談
CWを使ってせっかく高尚なボケがかまされたにもかかわらず、その内容に欠損が生じてしまったのが非常に悲しかったのです。

取り急ぎ報告します。

**Comment by yumetodo** [comment]
#101 と重複

**Comment by taro-hida** [comment]
確認したつもりが漏れてましたすみません。閉じます。
