### ISSUE TITLE
ヒント表示は入力ボックスではなく、アイコンをマウスオーバーしたときに出す

### ISSUE THREAD

**Issue by hidao80** [Qithub-BOT/mastogetter#47]
ヒントの表示はラベルの横に❓アイコンみたいのを置いてそこをマウスオーバーしたときに出したりするのが一般的かなと思いました（入力するたびにヘルプが出るのはつらい）by まちカドまえかわ さん

**Comment by yume-yu** [comment]
?アイコンのイメージ図
![スクリーンショット 2020-01-08 20 18 20](https://user-images.githubusercontent.com/30368684/71974731-93b5de00-3255-11ea-93f9-b8a2359f0ef0.png)

**Comment by hidao80** [comment]
@yume-yu いいと思います！👍

**Comment by woxtu** [comment]
@yume-yu 完全にこれです。

**Comment by hidao80** [comment]
@yume-yu これは #53 で対応していますか？ 別件ですか？

**Comment by yume-yu** [comment]
@hidao80 別件です

**Comment by yume-yu** [comment]
#83 では現状tootID/URL入力欄にのみヒントボタンを実装しているのですが、 それぞれの項目にヒントを設ける、もしくはこのページ自体の使い方ヒントを用意してしまうのもいいのかなと思いました。

**Comment by yume-yu** [comment]
とりあえず該当変更を含んだPRがmergeされたのでcloseします 🙇
