### ISSUE TITLE
[提案] 🦊🐦🐷.md の設置

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/mastogetter#54]
## コントリビューターのためのガイドライン

**CONTRIBUTING.md をルートに設置**してはどうでしょう？

> **リポジトリコントリビューターのためのガイドラインを定める**
>
> プロジェクトに人々がどのようにコントリビュートするべきかを伝えるガイドラインを作成できます。
>
> <sup>（『[リポジトリコントリビューターのためのガイドラインを定める](https://help.github.com/ja/github/building-a-strong-community/setting-guidelines-for-repository-contributors)』 @ GitHub ヘルプより）</sup>

[ATOM のガイドライン](https://github.com/atom/atom/blob/master/CONTRIBUTING.md)のようなガチマッチョなものでなくて、ブランチの役割やプルリクエスト（以下 PR）先くらいのもので良いと思うのです。

👍×3 or 5項目くらい挙がったら叩き台を作って `master` に PR したいと思います。

---

▼ 2020/01/10 18:00 更新

### 進捗

- 現在叩かれている 🦊🐦🐷ファイル → https://github.com/hidao80/mastogetter/pull/64/files

### 議題

- [x] 1. Linter をどうするか【済】
    - ~~JS には Linter は必要ではないか？~~ <br>→ #50 で ESLint の CI を実装済み。
- [x] 2. 基本ブランチをどうするか【済】
    - ~~そもそも `feature-dev` と `design-dev` にわける必要はあるのか？~~<br> → 今後は `gh-pages` と `master` の[２本立てブランチにする](https://github.com/hidao80/mastogetter/issues/54#issuecomment-572590606)。
- [x] 3. 作業ブランチ名の命名ルール【済】
    - ~~そもそもブランチに命名ルールを設ける必要があるか~~<br> → ~~#65 で議論中（投票受付中）~~<br> → ブランチの命名ルールは記載しない。ブランチ名よりはコミット・メッセージや PR 時の書き方の方が大事
- [x] 4. Draft PR 時に必要なコミット【済】
    - ~~→ https://github.com/hidao80/mastogetter/issues/54#issuecomment-572872373 で議論中~~<br> → ソースコードに概要をコメントして Draft PR を始める
- [ ] 5. コミット・メッセージの推奨する書き方
- [ ] 6. PR 時の推奨する書き方

**Comment by yume-yu** [comment]
タイトルで一瞬考えてしまった🤣
タブやインデント、エンコーディング、改行コードは `.editordonfig`が置いてあるのでそれを使うことを推奨してもらえると揃えやすそうですね。
jsはlinterの設定の共有とかがあるといいのかも?みなさんどうしているか気になります。
あとはブランチの役割とかも書いておくとPull requestを出す先の参考になりそう...!

**Comment by KEINOS** [comment]
@yume-yu 
> ブランチの役割とかも書いておくとPull requestを出す先の参考になりそう

なるほど！叩いてみました。

`gh-pages` `master` `design-dev` `feature-dev` の４者でクロスオーバーが発生しているので、`gh-pages` を最上位として `master` を中心とした流れにしてみましたがどうでしょう？

今は整理の段階なので、落ち着いたらこの運用という流れを考えています。


> js は linter の設定の共有とかがあるといいのかも

確かに。おいどんは VS Code にいつのまにか入れた JS Linter を無意識にかましちゃってますが、何かしらの基準があった方が安心ですねー。

タブスペースや改行ほどでなく、推奨レベルがいいのかしら。みなさんの意見も聞きたいところです。

**Comment by KEINOS** [comment]
「とりあえず、おいどんの Javascript の Linter 設定さらすか」と思ったのですが入っておりませんでした！

**Visual Studio Code の標準整形機能をオンにしていただけでした！！**（[基本設定]->[設定]->"Format" で検索すると出る Javascript の項目）。。。なんたルチア

<details><summary>キャプチャ画像</summary><div><kbd><img width="100%" alt="スクリーンショット 2020-01-09 13 14 26" src="https://user-images.githubusercontent.com/11840938/72037559-079dc800-32e2-11ea-945f-3fa0f78226a3.png"></kbd></div></details>

**Comment by KEINOS** [comment]
## JS Linter の提案（整形に関して）

Linter は各々の環境もあると思うので「Chrome の整形（`pretty-print`）機能を通すこと」はどうでしょう？

- 『[読みやすい形式への JavaScript の変換](https://developers.google.com/web/tools/chrome-devtools/javascript/pretty-print) 』| Web Developers Tools @ developers.google.com


Chrome のデベロッパーツールで `Sources` タブで該当 Javascript を開いて、左下にある `{}` ボタンを押すと整形されるので、それを Lint（整形）済みとみなす。

みたいな。

**Comment by yumetodo** [comment]
素直にESLint, stylelint, htmllintを掛ければいいのでは？CIで。

**Comment by hidao80** [comment]
lint は GitHub Action と CI の組み合わせにして、かつソースツリーへのライブラリ等の追加は最小限に抑えたいですね。
また、各自が lint 環境を用意せずに済む(CI を SaaS に任せる)、統一した仕組みが望ましいと考えています。

**Comment by yumetodo** [comment]
GitHub ActionかCircle CIかを気分で選べばいいと思います。どのみちnpmでlinter入れて、npm scriptをちょっと書いてあとはCiの設定書いて終わるので、どこでも・・・。

**Comment by hidao80** [comment]
@KEINOS 
> Javascript でラフな HTML+CSS で機能を実装したら、master にマージ後、design-dev でトドメを刺してもらう。
> design-dev からのモックが届いた（master にマージされた）らマージ後、トドメを刺す。

「`master`にマージ後、`design-dev`でトドメ」とありますが、

1. `master`に追加後、`design-dev`でコードの追加を行うという事でしょうか？
2. 「トドメ」とは具体的にどのような作業のことを考えておられますか？ `git branch -d desgin-dev`？

**Comment by yumetodo** [comment]
そもそも`feature-dev`と`design-dev`を分けるのって微妙な気がします。単にmasterがあればいいのでは(deployは`gh-pages`に別れたことですし)

だから

>https://qiitadon.com/web/statuses/103453021231539168
>(前フリ)
KEINOSさんが短縮したパーマリンクを表示する機能を作製
→ スタイルを用意する前にmasterにmerge
→ 当時はmasterが公開対象だったので急遽revert
→ feature-devはmerge直前で一旦更新ストップ
(ここから)
url短縮機能を含めてスタイルを調整するためにdesign-dev⬅️ feature-devからのpull requestを作製
→ 自分の説明が足りずhidaoさんからdesign-dev⬅️ masterのほうがいいのではと提案あり
→ 自分の意図を忘れてdesign-dev⬅️ masterのpullrequestを作製し、merge
→ design-devに短縮url機能がない←ｲﾏｺｺ
>
>です...

みたいなことが発生するわけで。

そもそも機能とデザインを分離可能としたところに問題があるように思われますがいかがでしょうか？

**Comment by hidao80** [comment]
@yumetodo  そうですね、昨日マージ地獄に陥って初めて機能ブランチとレイアウトブランチを分ける必要性のなさを痛感しました。
私なりに考えて、リリースは`gh-pages`、現在の修正結果をまとめたものを`master`と位置づけ、`master`に対して PR をしてもらうのが良いのではないかと考えています。ブランチ切るときも`master`のみから切ればロールバックの危険性も減らせると考えています。

> そもそも機能とデザインを分離可能としたところに問題があるように思われますがいかがでしょうか？

もともとはコーディング上の役割分担として「主に JavaScript の人」と「主に CSS の人」がいて、それぞれにブランチを切りましょうということだったのですが、現在 fork する開発体制になっているため形骸化している部分も大いにあります。

この辺りは本リポジトリ発生から現在まで数日しか経過していないので、制度設計の遅れと言われれば返す言葉もありません。

**Comment by KEINOS** [comment]
## 質問

それでは、基本的にブランチは `gh-pages`=リリース と `master`=最新 and DEV の２本ブランチで行くという方向でおk？

## 提案

Issue 対応（機能追加含む）ですが、Draft PR を使ってはどうでしょう？

- [Draft Pull Request をリリースしました](https://github.blog/jp/2019-02-19-introducing-draft-pull-requests/) @ GitHub Blog
- [WIPの代わりにDraft Pull Requestを利用する](https://qiita.com/tatane616/items/13da1b6797a7b871ad58) @ Qiita

これにより「この Issue に手を付け始めましたよ」ということが知らせられると思いますし、対応状況も把握しやすそうです。

また、#50 で本家に CI が実装されましたが、Draft PR の方法であれば本家 `master` への PR であるため CI が働くと思われます。つまり、Fork 側で用意しなくても CI を回せるということでもあります。

- 対応したい Issue を見つけたコントリビューターの作業
    1. 自身の Fork で Issue のブランチを作成。
    2. 未変更のまま `i` のブランチを本家の `master` に `Draft` で PR する。
    3. PR したブランチに Issue 対応をコミットしていく。（CI も同時に働く？要検証）
    4. レビュー可能になったら Draft を外して、レビュー依頼＆レビュー開始

**Comment by hidao80** [comment]
@KEINOS 
> ブランチは `gh-pages` と `master` の２本ブランチで行くという方向でおk？  
おｋ

> Draft PR を使ってはどうでしょう？
> これにより「この Issue に手を付け始めましたよ」ということが知らせられると思いますし、対応状況も把握しやすそうです。

やりましょう。やり方へのリンクを `CONTRIBUTING.md` に追記をお願いします。

> Draft PR の方法であれば本家 master への PR であるため CI が働くと思われます。

これは要検証です。私が使ってみた感じ、本家 master が更新（＝マージ）されたのをトリガーに CI が動いているようです。（CI 対象のブランチを任意に選択可）
そのため、CI は各自の GitHub アカウントで circle CI にアカウントを作って Fork リポジトリで CI を行ってから本家 master へ PR する流れになると思われます。

検証後、ドキュメントに反映ですね。イイ感じだと思います！💪

**Comment by yumetodo** [comment]
circle ciってあくまで個人の画面で動くと思います
他プロジェクトですが
https://github.com/Kasugaccho/DungeonTemplateLibrary
は
![image](https://user-images.githubusercontent.com/10869046/72076996-d9e46d80-3339-11ea-888b-cae0c612007e.png)
でCIが掛かってますが、自分が出したCIは特に何もせずとも
![image](https://user-images.githubusercontent.com/10869046/72077002-dcdf5e00-3339-11ea-8c26-9b2dbeb850d6.png)
のようにCIが掛かっていて
https://github.com/Kasugaccho/DungeonTemplateLibrary/pull/38
みたいな感じでGithub側では見えます

**Comment by hidao80** [comment]
@yumetodo 「個人の画面で動く」というのは「各個人のアカウントごとに、そのユーザのアカウントのリポジトリ内だけで CI する」というニュアンスでしょうか？

例えば、 @yumetodo さんが`hidao80:master`にプルリクしても、私の CI も @yumetodo の CI も走らないということなのでしょうか？

**Comment by yumetodo** [comment]
そうだったと記憶していますがちょっと試しに適当にPR投げてみますね。

**Comment by yumetodo** [comment]
いや、記憶違いらしい
https://github.com/hidao80/mastogetter/pull/62
動かん

**Comment by sasanquaneuf** [comment]
（こん・とり・ぶたの話じゃないけど）CIは通常はどのブランチでも動きますが、そのリポジトリの持ち主のアカウントでCircleCIに連携をして、かつ、そのプロジェクト（リポジトリ）を連携している事が条件です。
つまり、もしCircleCIにアカウント登録をしていない/プロジェクトを連携していないAさんが、hidao80/dokokano-branchにpushをした場合は動きます。しかし、Aさん自身のA/dokokano-branchやA/masterにpushをしてもCIは"通常は"動きません。プルリクも基本は同じですが、以下のような設定をするとビルドできます。
https://circleci.com/docs/ja/2.0/oss/#%E3%83%95%E3%82%A9%E3%83%BC%E3%82%AF%E3%81%95%E3%82%8C%E3%81%9F%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA%E3%81%8B%E3%82%89%E3%83%97%E3%83%AB%E3%83%AA%E3%82%AF%E3%82%A8%E3%82%B9%E3%83%88%E3%82%92%E3%83%93%E3%83%AB%E3%83%89%E3%81%99%E3%82%8B

**Comment by hidao80** [comment]
@sasanquaneuf とりま「[Build forked pull requests (フォークされたプルリクエストをビルド)] オプションをオンに設定」にしてみました。違うのかな？

**Comment by yumetodo** [comment]
どーも動かんので自分のは自分でセットアップしましたがうーん

**Comment by yumetodo** [comment]
>担当者名がない場合は「複数人で作業（他者コミット希望する）」、担当者名がある場合は「レビューまで担当者単独で作業（他者コミット希望しない）」の意思表示です。
>
>勝手がわからない同士の「あっ！まだ Push してないのに。チッ」といったことなどのポカよけ的なものです。

いや、やっぱりいらんのでは。そういうのはbranch名じゃなくてGithub上で解決されているわけで
というか原則PR投げてるbranchいじるのは一人で、それへの提案はPRページのSuggest機能とかもしくはそのbranchへのPRを投げればいいのではないかなと

**Comment by KEINOS** [comment]
Draft で PR #64 してみました。

> いや、やっぱりいらんのでは

あ！よく読んだら「担当者名」は必須になってる！！これは任意（`[]`）にするべきですね。

そもそも「ブランチ名にルールなんか設ける必要はあるのか」ということもあるので、本 Issue のファイル設置とは別件なので Issue を立てたいと思います。お待ちください。

**Comment by KEINOS** [comment]
### 議題

- Draft PR に関する手順の変更

どうやら、「まったく変更がない」場合は Draft PR も働かないようなので、**何かしら１つ変更をコミット& PUSH しないとダメ**なようです。

となると、問題は「叩き台をあげる（PR する）タイミング」になるかと思います。

### 提案

```diff
- **作業前**に、本家（Upstream）の master に PR してしまいます。
+ ソースの作業箇所付近や文頭に「作業の概要」をコメントします。
+ commit して push したら、そのまま本家（Upstream）の master に Draft で PR してしまいます。
```

Draft を使うポイントは「この Issue に手を付けたよ」という意思表示だと考えています。とくに本業のおてすきに Issue 対応を考えている場合には欲しい情報ではないでしょうか。

本来なら、ある程度作業をしてから PR するのが筋なのですが、「とりま TODO をコメントして Draft PR」が簡単かつ明示的な意思表示になると思います。

👍 × 3 or @hidao さんの裁量で反映します。

**Comment by yumetodo** [comment]
Draftはどっちかというとまだマージすんなよ！っていう表明だと思うのですが。

**Comment by KEINOS** [comment]
> @yumetodo 
> Draftはどっちかというとまだマージすんなよ！っていう表明だと思う

Draft の機能の発端が「マージ目的でない PR も可能にするためのもの」らしいです。

> 素晴らしいアイディアやコードが形になる準備ができたらすぐに、コラボレーターとの会話をスタートする Pull Request を開ける機能があれば良い
> ...
> 一方で、コードの完成度はまだ高くないけれど、コラボレーションをスタートするための会話として Pull Request を使用したいと思ったことはないでしょうか？
> 例えば、ハッカソンのプロジェクトでは、このような場面が想定できます。マージするためではなく、他のメンバーにローカルで確認してフィードバックをもらいたい場合、あるいはディスカッションを開始するために、コードを記載しないで Pull Request を開く場合もあります。
>
>（https://github.blog/jp/2019-02-19-introducing-draft-pull-requests/ より）

早い段階で Issue の意思表示をするというのは、Draft の機能を作るきっかけとなったらしい記事 の「[Open a Pull Request as early as possible](https://github.blog/2012-05-02-how-we-use-pull-requests-to-build-github/)」に影響を受けています。

つまり、「マージすんなよ！っていう表明」というより「マージできんぞ！っていう機能」だと思います。

その機能を、意思表示という目的のために使いたいな、という提案です。

ちなみに、GitHub では誰も Fork してないで同じリポジトリに PR してるんですって。

**Comment by KEINOS** [comment]
ということで、おいどんの 👍 も入れて 👍×3 と判断して「[Draft PR に関する手順の変更](https://github.com/hidao80/mastogetter/issues/54#issuecomment-572872373)」の議題は提案内容で一旦可決とします。

実際に Draft PR を使ってみてダメちんな場合は、別途 Issue を立てましょう。

**Comment by yume-yu** [comment]
Draft PRとは別件でガイドラインにほしい要素として、こっちで上がったように

https://github.com/hidao80/mastogetter/issues/65#issuecomment-572933559

commitメッセージの書き方も書き方というかテンプレートがほしいかもです。
例えば、
-  フォーマットとして`fix: hogehoge` みたいに操作を示す単語頭につけるかどうか
- つけるならどの単語をどんなときに使うか
- commitメッセージのメインの部分は英語で書くべきか

などなど

**Comment by KEINOS** [comment]
> @yume-yu 
> commitメッセージの書き方というかテンプレートがほしい

同意です。

 @yumetodo さんが教えてくださった[リンク先の「コミット・メッセージ規約」](https://github.com/asciidwango/js-primer/blob/master/CONTRIBUTING.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E8%A6%8F%E7%B4%84)をベースしたいと思います。ベースといっても、ほとんど丸パクリですがお互い MIT ライセンスなので大丈夫でしょう。

１点だけ、**`commit` メッセージのメイン（１行目）は基本的に日本語にしたい**と思います。

個人的に英語の方が楽なのですが、commit 一覧を見たときに日本語の方が把握しやすいと思ったからです。「英語の方がいい」という場合は、別途 Issue を立てましょう。

**Comment by KEINOS** [comment]
Draft PR #64 の「コミット・メッセージ」に関するガイドラインの進捗です。

- [コミット89f051c の CONTRIBUTING.md ](https://github.com/hidao80/mastogetter/blob/89f051cf9b23f292057e906e483f7f1c5cf00e57/CONTRIBUTING.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E6%99%82%E3%81%AE%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8)

**Comment by KEINOS** [comment]
[コミット 7b96b0e で CONTRIBUTING.md を設置した](https://github.com/Qithub-BOT/mastogetter/blob/7b96b0e29173a46f3716d404cc3a6a1f300046ca/CONTRIBUTING.md)ので Close しまーす。
