### ISSUE TITLE
readme に circle ci のバッジを載せたい

### ISSUE THREAD

**Issue by paihu** [Qithub-BOT/mastogetter#61]
せっかくCIまわるようになったのでバッジを

https://circleci.com/docs/ja/2.0/status-badges/

**Comment by hidao80** [comment]
@paihu うーん、やりたいのはやまやまなんですが、「html から呼び出されて js ファイルからは呼び出されることがない」関数とかが eslint では解消する方法がわからないんですよね…

無視してくれるオプションとかあればいいんですが、でなければ永遠にグリーンバッヂがもらえないという悲しみに暮れています…😥

**Comment by yumetodo** [comment]
それについては`addEventListenerを使う方向に書き換えるべきかと。

一応

```json
	"globals": {"moment": false},
```

のように書くことで消せますが、これはあくまで外部ライブラリに対して使うことを想定されていますので・・・。

**Comment by hidao80** [comment]
@yumetodo 
こういうおまじないを追記することで、esllint のエラーを抑制することができるようです。

```
/* global showCards, decodePermalink, get_url_vars, $ */ ←他のファイルで宣言されていることにする
/* eslint no-undef: "error" */ ←謎
/* exported showPreview */ ←このファイルで定義されており、一度も使用されていない変数・関数を他のファイルで使用されていることにする
```
現在検証中ですが、コードレビューを厳にすればうまくいきそうな感じです！

**Comment by yumetodo** [comment]
@hidao80 いや、根本的な解決を #62 でやってみました。

**Comment by KEINOS** [comment]
@paihu 
> せっかくCIまわるようになったのでバッジを

バッジを載せること自体は決定なようなので、とりまバッジを付けた PR をあげちゃってどうでしょう？

```
[![CircleCI](https://circleci.com/gh/hidao80/mastogetter.svg?style=svg)](https://circleci.com/gh/hidao80/mastogetter)
```
[![CircleCI](https://circleci.com/gh/hidao80/mastogetter.svg?style=svg)](https://circleci.com/gh/hidao80/mastogetter)

バッジがグリーンになれば１つ前に進んだってことにもなるし。

**Comment by sasanquaneuf** [comment]
新しいバッジよー　それー
[![CircleCI](https://circleci.com/gh/Qithub-BOT/mastogetter.svg?style=svg)](https://circleci.com/gh/Qithub-BOT/mastogetter)

**Comment by blhsrwznrghfzpr** [comment]
#62 で無事グリーンになったのでバッジを付けました :muscle:
