### ISSUE TITLE
ソース内の絶対パスをダイナミックに

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/mastogetter#68]
コミット 241b81d0053d0e0cb0d1162b820c5bf2074571b4 の時点で、パーマリンクの URL が絶対パスになっています。

https://github.com/Qithub-BOT/mastogetter/blob/241b81d0053d0e0cb0d1162b820c5bf2074571b4/js/common.js#L74-L81

MIT であるため派生 mastogetter も生まれる可能性もありますし、何よりローカルで確認する際にドメインのベース部分をローカルに書き換える必要もあります。

- 参考： https://qiitadon.com/web/statuses/103462233615180595

## 提案

- パーマリンクの URL のベースを、現在開いている URL のものにする。

**Comment by yumetodo** [comment]
forkして使う人のことを考えてもいいと思います

**Comment by yume-yu** [comment]
自分は賛成です。検証中や派生が生まれたあとに、固定だと確かに不便ですね。

**Comment by yumetodo** [comment]
#72 でリダイレクト実装するのにこれの解決が必須になりそうなのでこれもやります
