### ISSUE TITLE
バージョン1にv2のようなURL圧縮機能を互換性を維持したまま実装できないか

### ISSUE THREAD

**Issue by yumetodo** [Qithub-BOT/mastogetter#70]
>https://github.com/Qithub-BOT/mastogetter/pull/62#issuecomment-572853139
>話がそれますが互換性破壊せずともget paramの名前変えれば済んだのでは・・・？

と書いたのですが、get paramの名前変えるまでもなく互換性を維持できると思ったのでIssue立てました。

現状Get Paramは

- `i`: instance 名
- `t`: Toot id の配列(,区切り)

となっていると思うのですがv2で互換性を破壊したのは
https://github.com/Qithub-BOT/mastogetter/blob/241b81d0053d0e0cb0d1162b820c5bf2074571b4/v2/js/common.js#L118-L131
の処理を必ず適用していたためでした。
`_`を含めば36進数変換処理が入っていると区別ができるので単にその処理を追加すればよかったはずです。

つまり、まとめの表示とまとめ作成時の読み込み機能については両対応し、新規生成は36進数変換に変更すれば互換性は壊れていないものと思います。

Google検索にかけた感じ、`v2`は使われてる形跡がないので削除し、上記の様に統合しませんか？

**Comment by yume-yu** [comment]
その上で念の為すでに発行してしまったv2/も考慮して、v2/をメインにリダイレクトできるといいかなと思いました。どうでしょう

**Comment by blhsrwznrghfzpr** [comment]
統合する @yumetodo さんの案に賛成です👍
修正方針としても問題ないように思います

**Comment by yumetodo** [comment]
では作業します。
