### ISSUE TITLE
プレビューページで削除ができてしまう

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [Qithub-BOT/mastogetter#71]
# 確認環境
Windows10 + Chrome
コミット: de459630bacd3dd8fe0d7b8bf2c2cc1ed42e443a

# 現象
`https://qithub-bot.github.io/mastogetter/p.html` で表示される toot をダブルクリックで削除できてしまう

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/72200210-e2e45480-3489-11ea-81c4-644abfbc1c71.png)
あっ

**Comment by hidao80** [comment]
あたりはついて、修正中なんだけど Draft PR どうやって出すんじゃ…？

**Comment by yumetodo** [comment]
@hidao80 普通にPR出すときの緑のボタンの横の下▼を

**Comment by hidao80** [comment]
すみません、ちょっと解決しそうにないので一旦 PR 取り下げます。

**Comment by hidao80** [comment]
こっちは Issue だった💦
失礼しました。🙇‍♂️

**Comment by hidao80** [comment]
https://github.com/Qithub-BOT/mastogetter/blob/fe7fbf4b0bc207b4ce934fe494934cb38a484b60/js/common.js#L101

https://github.com/Qithub-BOT/mastogetter/blob/7b96b0e29173a46f3716d404cc3a6a1f300046ca/js/common.js#L131-L133

ここだと思われますが、`setAttribute("ondblclick")`は悪手なのでしょうか？

**Comment by yumetodo** [comment]
あんまりonclick attributeを使いたくないというか・・・。ちょっと私の方でも見てみます。

**Comment by yumetodo** [comment]
多分`showCards`の引数をいじりつつ、Event追加付近を共通化すれば行けると思うので、やってみます。
