### ISSUE TITLE
移管に伴う README.md の修正

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/mastogetter#74]
README.md のリンク先が生みの親のリポジトリになっているので、それ含め記述を直したいです。

---

2020/01/11 17:20 現在

- [x] ~~リンク先が親リポジトリになっている~~ → de45963 で修正済み
- [ ] Origin は @hidao80 さんである旨を盛り込む
- [ ] その他 → 緩募

**Comment by yumetodo** [comment]
https://github.com/Qithub-BOT/mastogetter/commit/de459630bacd3dd8fe0d7b8bf2c2cc1ed42e443a
で置換済では？

**Comment by KEINOS** [comment]
あ、ほんとだ。CONTRIBUTOR.md の PR で `master` から持ってくる前に見たんだな。遺憾遺憾。移管だけに。

ただ、オリジナルは @hidao80 さんから始まったことなどを盛り込みたいと思います。

他に [`7b96b0e2` 現在の README.md](https://github.com/Qithub-BOT/mastogetter/blob/7b96b0e29173a46f3716d404cc3a6a1f300046ca/README.md) で気になる項目があったら緩募します。
