### ISSUE TITLE
netlifyの導入

### ISSUE THREAD

**Issue by yumetodo** [Qithub-BOT/mastogetter#75]
netlify.comを使うとPRに対して自動的にpreview用のWeb siteを作ってくれる。
例としては
https://github.com/asciidwango/js-primer/pull/1005
というPRに対してbot-userが生成完了を教えてくれて
https://deploy-preview-1005--js-primer.netlify.com/
みたいにPR番号を含むURLを吐いてくれる。

レビューしやすくなるのではないか。

**Comment by KEINOS** [comment]
おぉ、これは圧倒的にレビューしやすいですね！
Free でも branch preview 入ってるので使えると思います。

ちょっと試してみますか。

**Comment by KEINOS** [comment]
なんかアカウント登録して Fork の方で試す予定だったのに、アクセス権で Organization（Qithub-BOT）も有効にしたら mastogetter も有効になっちゃった。。。

とりあえず様子見。カオスになるようだったらこの Issue で話しましょう。

**Comment by blhsrwznrghfzpr** [comment]
とてもレビューしやすくなりました 👍 
@KEINOS 間違いとは言え導入してしまったんで、この Issue は一旦 close して、
問題が発生したら re-open することにしませんか？

**Comment by KEINOS** [comment]
そうですね。それでは一旦 Close し 💪💪
