### ISSUE TITLE
URL 欄をクリックしたら選択状態にして欲しい

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/mastogetter#76]
編集画面の「トゥートID or URL」で、URL をコピペするときに１つ前の URL があった場合、いったん全文選択 or 削除しないとペーストが差し込みになってしまう。

フィールドをクリック（フォーカス）が当たったら全文選択（`ctrl+a` or `⌘+a` を押した）状態にして欲しい。

<kbd><img width="100%" alt="スクリーンショット 2020-01-11 19 46 31" src="https://user-images.githubusercontent.com/11840938/72203267-af66f180-34ac-11ea-9a81-1f2bd1037918.png"></kbd>

**Comment by sasanquaneuf** [comment]
こういうやつでできます
https://developer.mozilla.org/ja/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
ただ、ドキュメントにもある通り、clickとかfocusとかユーザーの行為がトリガーになっていないと動かないので、実装に少し注意が必要かもしれません

**Comment by blhsrwznrghfzpr** [comment]
クリップボードの操作じゃなくて、ただ選択状態にするだけでいいと思うので、
下記を利用すればいいと思います。
https://developer.mozilla.org/ja/docs/Web/API/HTMLInputElement/select

これから実装します

**Comment by sasanquaneuf** [comment]
ああそっか、そうですね、すみません
