### ISSUE TITLE
トゥートの並び順をフリップできるようにして欲しい

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/mastogetter#77]
現在、まとめの並びが追加順（古い→上、新しい→下）になっています。この並びを逆転フリップする機能が欲しいです。

追加順になること自体はいいのですが、TL を過去に辿りながら追加していった時に、全体の並びを逆にしたくなります。

少数ならドラッグ＆ドロップできるのですが、数が多いと並び順もわからなくなり投稿時間を見ないといけなくなります。

まぁ、「TL の一番古い順から現在にさかのぼって追加していけ」と言えば、そうなんですが。追加して見直した時に、逆の方がいいな、と思って。

**Comment by yume-yu** [comment]
@KEINOS  要素の順番を保持したままでいいのであればflex-directionで表示上の順番が入れ替えられるのですが、実データも入れ替わったほうが都合がいい感じだと思うのですがどうでしょう

**Comment by blhsrwznrghfzpr** [comment]
#81 にて解決
