### ISSUE TITLE
トゥートの追加をトップに（FIFO but 条件付き）

### ISSUE THREAD

**Issue by KEINOS** [Qithub-BOT/mastogetter#80]
編集画面でトゥート追加時、従来の最下部に追加していくのでなく、上部に追加していく方法にできないか。

であれば、 編集フォームのすぐ隣に追加したトゥートが表示されるので #78 の「追加したことが目視できる」ことにもなると思います。

しかし、これには条件があって #77 の順番のフリップが実装されてから意味があるのかもしれません。

また、上に足すか下に足すかの**選択オプションを付けるは煩雑になるので付けたくありません**。

わがままですよね。難しい。とりあえず、以下の Issue も見ながらアイデアを練っていきたいと思います。

- #76 URL 欄をクリックしたら選択状態にして欲しい
- #77 トゥートの並び順をフリップできるようにして欲しい
- #78 「トゥートを追加」したらアウトフォーカスもしくはシグナルが欲しい

**Comment by yume-yu** [comment]
これに関して、 過去に
> まとめが出来るところにoverflow: scrollを付けて、トゥートを追加したらすぐ横で見れるようにしたいなぁ。
> 長いまとめ作ると下に一回スクロールして確認して上に戻って追加することになったから。
https://qiitadon.com/@whendidyousee/103448625966599263

こんなtootがあり、 #78 に加えて「tootの追加メニューが最新の追加tootに追従する」仕様が実現できるので自分としてはこっちがいいかなと。
一応要素の上下逆順並び替えはcssで再現できるので並び替え(とスイッチでの切り替えも)実現は可能です 💪

**Comment by KEINOS** [comment]
なるほどー。

スクロールは全体の流れをチェックするのにも必要なので、それ自体は苦ではないのですが「トゥートを確認してトップに戻るのループ」という行為が問題だったんですねー。

`overflow: scroll` ってインラインフレームみたいなやつですよね？

追加したら、アンカークリックのようにスクロールされて、すぐ隣までくる、と。

そうなると、「追加されたことが目視できる」ということなので #78 も同時にクリアされる、と。

したらば、最上部に追加する必要もなくなる、と。

いいと思います！！とてもデリシャス。

**Comment by KEINOS** [comment]
まとめ一覧のエリアが今後スクロールされるのであれば**トップに追加する必要はない**ため、一旦この Issue は close させていただき 💪

-> p.s. @yume-yu
