### ISSUE TITLE
ESLint: Lower Camel Case に統一してはどうか

### ISSUE THREAD

**Issue by yumetodo** [Qithub-BOT/mastogetter#84]
JavaScriptのProjectでは一般にcamel caseを採用することが多く、ESLintもcamelCaseであることを要求するルールはあるものの
https://eslint.org/docs/rules/camelcase#
snale_caseであることを要求するルールは存在しません。もちろんそういうpluginはあった気がしますが。

そこでcamelCaseを採用することで統一してはどうかと提案します。

**Comment by KEINOS** [comment]
私も lowerCamelCase に１票

個人的に Snake でも Pascal でも Camel でも、全体で統一されていれば気にしない派です。

**Comment by sasanquaneuf** [comment]
私個人は、みんながどうするかという意味では"何でも良い"と思いますが、後で方針変更すると大変なので、今のうちに方針は決めておいた方がよいのかなと思います。

コーディング規約は、しっかりしている方が良いという人もいればそうでない人もいるので、実際に書いている人の好みで決めればよいのかなと思います。ただ、一般的なやり方に慣れた方が、今後に向けた経験という意味ではよいような気がします。特に何か強い思いがあるわけではないので、自由に決めてください。

**Comment by yume-yu** [comment]
jsのContributorのみなさんがcamelCaseに異議がなければ、 @sasanquaneuf さんの言う通り統一することに意味がありそうなのでサクッとeslintの設定とリファクタリングしちゃっていいかもです。
@blhsrwznrghfzpr さんお手すきで確認してもらって、いいかなと思えたらGOをだしてもらえるととりかかれそうです 🙏

**Comment by yumetodo** [comment]
うーん、ESLint手を出すなら、JavaScriptいじってる #72 #73 をmergeかrejectされてからにしてもらえると個人的には嬉しいです。

**Comment by yume-yu** [comment]
たしかに:flushed:
対応は#73 が済んでからの方が良さそうですね

**Comment by KEINOS** [comment]
#73 は一旦 close されてるからいいとして、おいどんも Draft PR だけ投げておいて #72 が済んでから手をつけはじめるのが無難だと思います。

**Comment by KEINOS** [comment]
べつに PR 投げておかなくてもいいのか。

**Comment by yumetodo** [comment]
ミスった、 #73 じゃない、 #85 だ

**Comment by yume-yu** [comment]
@yumetodo  「js絡みのPRを処理してからeslintの整理をしたほうがいい」ってことですよね。たぶんニュアンスは伝わってます 👍

**Comment by blhsrwznrghfzpr** [comment]
ESLint の設定については、がっつり考え始めると疲弊してしまいそうなので、
オプションが必要と思った人がリファクタしてくれればいいと思います。

個人的には何も考えずにメジャーな設定
( [Google JavaScript Style Guide](https://github.com/google/eslint-config-google), [JavaScript Standard Style](https://github.com/standard/eslint-config-standard), [Airbnb JavaScript Style](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) など）
を使えばいいのかなとは思いますが、
どれにするか決めるのも疲弊しそうなので、やりたい人が自由にやってください。

**Comment by KEINOS** [comment]
個人的にこう言う Style が好きです。https://youtu.be/99EDUkQuzd4

**Comment by yumetodo** [comment]
@KEINOS ブラウザバックしました

**Comment by yumetodo** [comment]
Google JavaScript Style Guideってこれでちゃんとメンテしてるのか・・・？deprecatedになってるルール入っている(valid-jsdocをみつつ)

**Comment by KEINOS** [comment]
[JavaScript Standard Style](https://github.com/standard/eslint-config-standard9) でいいんじゃないですかね？ Node.js、npm、GitHub も[使っている](https://standardjs.com/#who-uses-javascript-standard-style)みたいですし。

**Comment by yumetodo** [comment]
すでに書いているルールとの整合性を確認します。

**Comment by sasanquaneuf** [comment]
じつは最初に入っていたのがstandardjsでした、ただタブとかは変更してましたが。
多少のリファクタは必要になりますね。

**Comment by yumetodo** [comment]
そうそう。あれからコード増えてるのでどうなるかなという所。

**Comment by yumetodo** [comment]
いや、でstandardjsするのはまあいいとして結局最初の話しであったcamel caseの話しはどうなりましたでしょうか？

ESLintデフォルトのルールでは全部camelCaseにする(関数名も変数名も)しかないようです。また多くのJavaScriptプロジェクトではそれを採用しています。

なんにせよ統一しておいたほうがコードが読みやすいと思うので、 @blhsrwznrghfzpr さんがどう思っているのか聞きたいです。 @KEINOS さん、 @sasanquaneuf さんは統一されれば何でもというスタンスだと把握しています。

**Comment by blhsrwznrghfzpr** [comment]
分かりづらい書き方をして申し訳ないです。

（camel caseを含む）あらゆるeslintのオプションは設定したい人が設定してリファクタしてくれたら何でもいいです。
