### ISSUE TITLE
Toot IDに対する制約は間違いなのではないか

### ISSUE THREAD

**Issue by yumetodo** [Qithub-BOT/mastogetter#90]
from #72 

現在、Toot IDについて「1.0+E18より小さければ、id の途中で url が切れたと判断してエラーに」という仕様があるが、これは誤りではないか。

反例: https://qiitadon.com/@tomoasleep/1

**Comment by sasanquaneuf** [comment]
そうですね、他のidのトゥートが引っかかってるのかなと思いましたが、そうではなくて本当にid=1のトゥートが存在していますね。

**Comment by yume-yu** [comment]
これは #88 の実装にも関連しそうなので気になります:eyes:

**Comment by yumetodo** [comment]
https://qithub-bot.github.io/mastogetter/p.html?i=https://qiitadon.com&t=4901,4912,4987,4989,4990,4991,5000,5211,5555

これを見てみると全部ってわけではないけど小さい数字のが見受けられます。

多分MastdonのTooT ID生成にどっかのタイミング(v1.3付近？)でbreaking chnageが入ってると思われます。証拠を見つけてないですが。

**Comment by yumetodo** [comment]
id途切れを捕捉する事自体をやめるべきだと思います。どうしてもid途切れを捕捉するならid listのhashかなにかを取るべきではないでしょうか。

**Comment by yume-yu** [comment]
urlへの対応はラフに実装した部分たったと思うので、必要ならば変えてしまっておっけーだと思います

**Comment by yumetodo** [comment]
https://github.com/Qithub-BOT/mastogetter/commit/955beedcca36ead051dedebd3d1a8af17712e60b

このcommitですね。
cc: @hidao80

**Comment by KEINOS** [comment]
数桁の ID があるのは、私も以前自分のトゥート全消しをスクリプトでした際に気づきました。

ある時点からトゥートの ID の振り方が大幅に（桁数が）変わっています。創造主のオイゲンさんがそういう仕様にしたので、仕様がない。おそらく Mastodon が Activity Pub 対応の準備をはじめたあたりかと。

数桁の PubSubHubBabu（WebSub?） 時代は、おいどんも知らない前世代なので遺跡を掘る感じで面白いですね。1.0+E18 は、１つの時代の区切り線なのかもしれません。

https://qithub-bot.github.io/mastogetter/p.html?i=https://qiitadon.com&t=1,2,3,4,5

遺跡トゥートも API で拾えてきてるし、私も必要なら変えてしまっておkだと思いまーす。

**Comment by yumetodo** [comment]
では変える方向で #72 で実装します。

**Comment by yumetodo** [comment]
実装しました

**Comment by KEINOS** [comment]
はやっ！

**Comment by yumetodo** [comment]
もともとこれのために冗長なコードが必要になってたのでついでにスッキリ。
