### ISSUE TITLE
Tabnabbingの脆弱性

### ISSUE THREAD

**Issue by prograti** [Qithub-BOT/mastogetter#91]
target="_blank"を使っている箇所がいくつかありますが、target="_blank"はrel=”noopener”とセットで使うべきかと思います。

**Comment by yumetodo** [comment]
そもそも`target="_blank"`は必要ですかね？一時期(2012年頃？)、新しいタブで開くかどうかはユーザーに選択する権利をもたせるべきだみたいな論調が主流になったと思うんですが(最近は知らない)

**Comment by sasanquaneuf** [comment]
どちらかというとtarget="_blank"のほうが便利には思われます。
本家togetterもそうなっていますね。ちなみにrel="noopener"がついてないのも同じ、、
![ほんけ](https://file.qiitadon.com/media_attachments/files/002/068/224/original/1e92c6d59bd915a0.png)

**Comment by KEINOS** [comment]
> そもそもtarget="_blank"は必要ですかね

Issue とは別件ですが `_blank` でなくてもリンクは別タブにして欲しいです。

長いまとめを触るとわかりますが、ページが別タブでなく遷移しちゃうと戻ってくるたびに重いのです。（ちなみにトゥート内のリンクが同じインスタンスドメインの場合は `target=_bank` は効いてません）

閑話休題

> `target="_blank"` は `rel=”noopener”`とセットで使うべき

これ自体には同意です。ただ、現在の動きは相手の Mastodon API のバージョンにもよる気がします。

mastogetter のトゥート本文の表示にはおそらく API の `content` の要素の内容をそのまま使ってると思います。以下は API のレスポンスですが、サーバーによってはアンカーに `rel=\"nofollow noopener\" target=\"_blank\"` を指定しています。

https://paiza.io/projects/BJFF9fHVUIyP6SL1xNromA

そのため、トゥートを流し込む時に `a` タグには `rel=\"nofollow noopener\" target=\"_blank\"` の attribute を確実に挿入するようにすれば無難かと。

**Comment by KEINOS** [comment]
`rel="nofollow"` は、トゥートしたユーザーの意図した設定なので別 Issue でディスカッションすべきかもしれません。「Mastodon にクローラーに晒されたくない場合の設定があり、そう設定しているのに、まとめで晒された」という炎上に繋がるからです。似たようなことが昔 FTL でも昔議論になった気がします。

**Comment by sasanquaneuf** [comment]
common.jsのL114とL119
https://github.com/Qithub-BOT/mastogetter/blob/master/js/common.js#L114
https://github.com/Qithub-BOT/mastogetter/blob/master/js/common.js#L119
は自前で指定しているので、それは(nofollow)+noopenerを指定する必要はあります。

rel="nofollow"で晒された問題は、そもそもリンクを貼っている時点で晒されているのと、一方でwwwに公開したコンテンツを晒すも何もという感じはありますが、、、ちゃんと議論するとしたら別issueで、ここでは最低限noopenerは付与する必要がありますね。面倒ならnofollowもつけておいてから、別issueで議論とかでいい気もしますが

**Comment by sasanquaneuf** [comment]
mastodon側でcontentの中のa要素にnoopenerがついていたりいなかったりする場合は、contentの中をちゃんと編集するんでしょうね

**Comment by yumetodo** [comment]
どのバージョンのmastodonが動いているか保証がないので、自力でやるのは必要そう

**Comment by KEINOS** [comment]
確かに。自前で指定している箇所は `(nofollow)+noopener` 必要ですね！

> 最低限 noopener は付与する必要がありますね。面倒なら nofollow もつけておいてから、別 issue で議論とかでいい気もします

`content` の中身に関しては、確かに保証がないので自力でやる必要はあるかも。

`noopener` は必須として、余計なトラブルのもとなので `nofollow` はデフォルトで付ける方向でいいんじゃないかしら。

「晒して欲しい」（`nofollow` を外して欲しい）という、露出狂からの要望が出てきたら、そん時に Issue をあげてもらうということで。

**Comment by yumetodo** [comment]
まあ`nofollow`についてはつけていいんじゃないですかね。
