### ISSUE TITLE
同じIDのトゥートを2つ登録してからダブルクリックで削除すると、画面上では1つしか消えないが2つ削除されている

### ISSUE THREAD

**Issue by sasanquaneuf** [Qithub-BOT/mastogetter#92]
内容は表題の通り。下記画像参照。
＜再現手順＞
１．index.htmlでトゥートをいくつか登録し、同じIDを複数含む状態にする。
![画像１](https://file.qiitadon.com/media_attachments/files/002/068/537/original/df7bd374c3b761d4.png)
２．複数含まれるIDのトゥートを一つダブルクリックすると、画面上は一つだけ削除されるが、URLは複数削除されている。
※とりあえずURLずれてるけど、他にも影響あるかも？
![画像２](https://file.qiitadon.com/media_attachments/files/002/068/538/original/192862609fabf7a8.png)

**Comment by yumetodo** [comment]
これって #72 での話ですか・・・？

**Comment by yume-yu** [comment]
見えてるアドレス的には #72 っぽいですね

**Comment by yumetodo** [comment]
![image](https://user-images.githubusercontent.com/10869046/72265701-517b0b00-3660-11ea-8bac-8b18170c910a.png)
![image](https://user-images.githubusercontent.com/10869046/72265716-550e9200-3660-11ea-9c4b-7f18cd034615.png)
つまり`delete card_list[index];`が悪い。

**Comment by yumetodo** [comment]
https://github.com/Qithub-BOT/mastogetter/commit/d50e36afe4304f53e166b15e83058ddce71da7e8#diff-42f69825340f0b5fa628d80900a46daaL65-R85

#62 で私がやらかしてた

**Comment by sasanquaneuf** [comment]
いちおう、再現したのは#72のやつでしたが、 https://qithub-bot.github.io/mastogetter/ でもおかしくなりました。

**Comment by yumetodo** [comment]
直します。

**Comment by yumetodo** [comment]
修正投げました。
